import pandas as pd

from data_loader import load_transaction_data


# -----------------------------
# Load prepared transaction data
# -----------------------------

transactions = load_transaction_data()


# -----------------------------
# Select July & August 2026
# -----------------------------

july = pd.Period("2026-07")
august = pd.Period("2026-08")

comparison = transactions[
    transactions["month"].isin([july, august])
].copy()


# -----------------------------
# Customers active in each month
# -----------------------------

july_customers = set(
    comparison.loc[
        comparison["month"] == july,
        "customer_id"
    ].unique()
)

august_customers = set(
    comparison.loc[
        comparison["month"] == august,
        "customer_id"
    ].unique()
)


# -----------------------------
# Customer groups
# -----------------------------

retained_customers = (
    july_customers
    & august_customers
)

churned_customers = (
    july_customers
    - august_customers
)

new_or_returning_customers = (
    august_customers
    - july_customers
)


# -----------------------------
# Customer counts
# -----------------------------

july_customer_count = len(july_customers)
august_customer_count = len(august_customers)

retained_count = len(retained_customers)
churned_count = len(churned_customers)
new_or_returning_count = len(
    new_or_returning_customers
)


# -----------------------------
# Retention & churn rates
# -----------------------------

retention_rate = (
    retained_count
    / july_customer_count
    * 100
    if july_customer_count > 0
    else 0
)

churn_rate = (
    churned_count
    / july_customer_count
    * 100
    if july_customer_count > 0
    else 0
)


# -----------------------------
# Revenue by customer group
# -----------------------------

july_revenue = (
    comparison[
        comparison["month"] == july
    ]
    .groupby("customer_id")["line_total"]
    .sum()
)

august_revenue = (
    comparison[
        comparison["month"] == august
    ]
    .groupby("customer_id")["line_total"]
    .sum()
)


# -----------------------------
# Revenue lost from churned customers
# -----------------------------

churned_revenue_loss = (
    july_revenue
    .reindex(
        churned_customers,
        fill_value=0
    )
    .sum()
)


# -----------------------------
# Revenue generated by retained
# customers in August
# -----------------------------

retained_august_revenue = (
    august_revenue
    .reindex(
        retained_customers,
        fill_value=0
    )
    .sum()
)


# -----------------------------
# Revenue generated by
# new/returning customers
# -----------------------------

new_returning_august_revenue = (
    august_revenue
    .reindex(
        new_or_returning_customers,
        fill_value=0
    )
    .sum()
)


# -----------------------------
# Display analysis
# -----------------------------

print("CUSTOMER RETENTION & CHURN ANALYSIS")
print("===================================")


print()
print("CUSTOMER BASE")
print("-------------")

print(
    f"July customers          : "
    f"{july_customer_count}"
)

print(
    f"August customers        : "
    f"{august_customer_count}"
)


print()
print("CUSTOMER MOVEMENT")
print("-----------------")

print(
    f"Retained customers      : "
    f"{retained_count}"
)

print(
    f"Churned customers       : "
    f"{churned_count}"
)

print(
    f"New/Returning customers : "
    f"{new_or_returning_count}"
)


print()
print("RETENTION METRICS")
print("-----------------")

print(
    f"Retention rate          : "
    f"{retention_rate:.2f}%"
)

print(
    f"Churn rate              : "
    f"{churn_rate:.2f}%"
)


print()
print("REVENUE IMPACT")
print("--------------")

print(
    f"Revenue lost from churn : "
    f"₹{churned_revenue_loss:,.2f}"
)

print(
    f"August revenue from "
    f"retained customers     : "
    f"₹{retained_august_revenue:,.2f}"
)

print(
    f"August revenue from "
    f"new/returning customers: "
    f"₹{new_returning_august_revenue:,.2f}"
)